# General Settings
title: Coding with Nadewell
email: nishant.shaligram@gmail.com
description: "Welcome to my new blog running on Jekyll"
baseurl: ""
url: ""

collections:
  authors:
    output: true
  courses:
    output: true
  html5:
    output: true
  css3:
    output: true
  javascript:
    output: true
  flutter:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "html5"
    values:
      layout: "chapter"
  - scope:
      path: ""
      type: "css3"
    values:
      layout: "chapter"
  - scope:
      path: ""
      type: "javascript"
    values:
      layout: "chapter"
  - scope:
      path: ""
      type: "flutter"
    values:
      layout: "chapter"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  - scope:
      path: ""
    values:
      layout: "default"
      is_page: true

plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap