collections:
  authors:
    output: true
  courses:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  - scope:
      path: ""
    values:
      layout: "default"
      is_page: true