# General Settings
title: Coding with Nadewell
email: nishant.shaligram@gmail.com
description: "Welcome to my new blog running on Jekyll"
baseurl: ""
url: ""

collections:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  - scope:
      path: ""
    values:
      layout: "default"
      is_page: true

plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap